"""`myg prompt` — agentic edits to an existing generated app.

Default backend: Claude Agent SDK (local, streaming, uses the user's Anthropic
key or Claude subscription). `--backend devin` fires an async Devin session.
"""

from __future__ import annotations

import asyncio
import os
from pathlib import Path
from typing import Annotated

import httpx
import typer
from rich.console import Console

from myg.context import find_project_root

console = Console()

_SYSTEM = """You are myg's in-app editor: an agent that modifies an app generated by `myg init`.
Layout:
- apps/web  — Next.js + CopilotKit + Tailwind v4 + Biome (lint+format)
- apps/agent — FastAPI + LangGraph over AG-UI; agent patterns in src/agent/patterns/
- infra/gateway — Kong decK config (present only if gateway enabled)
- myg.toml — the project config; update it if you change config-facing values
Rules: minimal, idiomatic, production-shaped changes. Concise inline docs only.
Match existing style: ruff/black for Python, biome for TypeScript.
"""


def prompt(
    instruction: Annotated[str, typer.Argument(help="What to change, e.g. 'make the UI sexier'")],
    backend: Annotated[str, typer.Option("--backend", help="claude|devin")] = "claude",
    model: Annotated[str | None, typer.Option("--model")] = None,
    project_dir: Annotated[Path | None, typer.Option("--dir", "-d")] = None,
) -> None:
    """Tell myg to change your app in plain English."""
    root = (project_dir or find_project_root()).resolve()
    if backend == "devin":
        _devin(instruction, root)
        return
    try:
        import claude_agent_sdk  # noqa: F401  # pyright: ignore[reportMissingImports]
    except ImportError:
        console.print(
            "[red]Claude Agent SDK not installed.[/red]\n"
            "Run [bold]pip install 'myg[agent]'[/bold], or use [bold]--backend devin[/bold]."
        )
        raise typer.Exit(1) from None
    asyncio.run(_claude(instruction, root, model))


async def _claude(instruction: str, root: Path, model: str | None) -> None:
    from claude_agent_sdk import (  # pyright: ignore[reportMissingImports]
        AssistantMessage,
        ClaudeAgentOptions,
        ResultMessage,
        TextBlock,
        query,
    )

    toml = (root / "myg.toml").read_text(encoding="utf-8")
    options = ClaudeAgentOptions(
        cwd=str(root),
        allowed_tools=["Read", "Write", "Edit", "Bash", "Glob", "Grep"],
        system_prompt=_SYSTEM + "\nmyg.toml:\n" + toml,
        permission_mode="acceptEdits",
        model=model,
    )
    async for message in query(prompt=instruction, options=options):
        if isinstance(message, AssistantMessage):
            for block in message.content:
                if isinstance(block, TextBlock):
                    console.print(block.text)
        elif isinstance(message, ResultMessage):
            console.print(f"\n[dim]{message.subtype}[/dim]")


def _devin(instruction: str, root: Path) -> None:
    key = os.getenv("DEVIN_API_KEY")
    if not key:
        console.print("[red]DEVIN_API_KEY not set.[/red]")
        raise typer.Exit(1)
    task = f"Working directory contains a myg-generated app.\n\n{_SYSTEM}\n\nTask: {instruction}"
    resp = httpx.post(
        "https://api.devin.ai/v1/sessions",
        headers={"Authorization": f"Bearer {key}"},
        json={"prompt": task},
        timeout=30,
    )
    if resp.status_code >= 400:
        console.print(f"[red]Devin API error {resp.status_code}: {resp.text[:300]}[/red]")
        raise typer.Exit(1)
    data = resp.json()
    console.print(f"[green]Devin session started:[/green] {data.get('url', data)}")
